### PR TITLE
Release checklist

### PR DESCRIPTION
**Pull request by hugovk**
How about something like this? Comments welcome!

### CODE REVIEW

**Comment by kryysler** [comment]
Wouldn't https://guides.github.com/introduction/flow/ work for this? basically the same thing, but we can skip the "develop" branch, and do features/bug fixes in branches made from master? It would mean that every new feature/bug fix is a "new release" (tag).

**Comment by soderluk** [comment]
I agree with @kryysler. We could start using GitHub Flow on these projects.

**Comment by cniska** [comment]
Sounds good to me. However I would prefer [Passport](https://laravel.com/docs/5.4/passport) over this library. Not sure how well it plays with Lumen though.

**Comment by hugovk** [comment]
GitHub Flow looks good. 

It doesn't really apply here, but it says to deploy the feature branch to production *before merge*.

> # Deploy
>
> Once your pull request has been reviewed and the branch passes your tests, you can deploy your changes to verify them in production. If your branch causes issues, you can roll it back by deploying the existing master into production.

**Pull request closed without merging**
